# SPDX-License-Identifier: CC0-1.0

[project]
name="gabel"
description="Gabel, the static site generator for gabl.ink"
version="0"
requires-python=">=3.10"
dependencies=[
  "langcodes"
]
authors=[
  {name="Gabriel “gabldotink”",email="gabl@gabl.ink"}
]
license="CC0-1.0"
classifiers=[
  "Development Status :: 2 - Pre-Alpha",
  "Natural Language :: English",
  "Private :: Do Not Upload",
  "Programming Language :: Cython",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
  "Topic :: File Formats :: JSON"
]

[project.urls]
Repository="https://github.com/gabldotink/gabl.ink_dev"
Issues="https://github.com/gabldotink/gabl.ink_dev/issues"
